### ISSUE TITLE
Trouble importing iMedia.h header in ARC environment

### ISSUE THREAD

**Issue by tonyxiao** [karelia/iMedia#37]
When the main project is using ARC, trying to `#import <iMedia/iMedia.h>`  generates compiler errors about objects in structs  as well as autorelease messages. What's the recommend way to fix this?

![Error Message](http://f.cl.ly/items/0o2O0d0k2m3h393d2r3R/Screen%20Shot%202012-01-03%20at%203.16.17%20PM.png)

**Comment by jfahrenkrug** [comment]
ARC-support out of the box would be awesome :)

**Comment by mikeabdullah** [comment]
This has been resolved now, right?

**Comment by jfahrenkrug** [comment]
Yes!
