### ISSUE TITLE
Mountain Lion - iMedia2 Tester Impossible to add photos previously taken on Photo Booth

### ISSUE THREAD

**Issue by mazen-kasser** [karelia/iMedia#70]
Description

Issue: You can't add photos previously taken by Photo Booth in the album; you need to access Photobooth via the project to be able to take photos, and redo this for each new window you want to fill.

Repro Steps:
1/ Take photos with Photobooth without opening the project
2/ Open any the iMedia project
3/ Try to add the photos already taken: impossible
4/ Go to Photobooth via the iMedia sidebar
5/Take a photo with Photobooth then add it in the photo box : it works

Expected:
You should be able to place photos whenever they were taken, whatever software was used

Actual:
You need to go back to Photobooth via the Add Media to take a photo and add it in the photo box at each new photo box you want to fill...

**Comment by mikeabdullah** [comment]
Hello, I'm struggling to understand the last of your repro steps here. What exactly do you mean by "Add it in the photo box"?

**Comment by mazen-kasser** [comment]
The actual bug is that when you run iMedia2 on Mt Lion, you won't be able to drag and drop media from the media browser to the project window. I think our developers figured it out, but I'm sure your fix would be better.

**Comment by mikeabdullah** [comment]
OK, what do you mean by "the project window"? Are you having problems dragging into your app specifically, another app, or iMedia's tester window?

**Comment by mazen-kasser** [comment]
I mean iMedia Tester Window... Try it on Mt Lion and see... For us we don't need it anymore as our developers fixed it

**Comment by mikeabdullah** [comment]
Well that's odd, I tried that and it worked for me! What source in the browser were you dragging from?

**Comment by mazen-kasser** [comment]
Normal media like photos from the desktop if you try to drag it from the "iMedia Tester media broswer" to the "iMedia tester window" with using Mouintin Lion. It wont work unless u drag direcly from the desktop to the "iMedia Tester Window". But our developers said that this is a sandbox issue so they used an alternative way for d pasteboard.
