### ISSUE TITLE
iTunes Artworks Problem

### ISSUE THREAD

**Issue by loretoparisi** [karelia/iMedia#86]
It seems that not all the mp3 files icons are being loaded by the framework.
How to debug that?

Regression:
MacOS X 10.8.2
iTunes 11

**Comment by loretoparisi** [comment]
Found out the problem in the thumbnail image size:

   (File: NSURL+iMedia)

```
  -(CGImageRef) imb_quicklookCGImageIfAvailable
```

   {
       if ([NSThread isMainThread])
       {
        NSLog(@"%s is being called on main thread. We probably want to re-do this for background thread",          **FUNCTION**);
            }

```
CGSize size = CGSizeMake(kIMBMaxThumbnailSize,kIMBMaxThumbnailSize);
CGImageRef image = QLThumbnailImageCreate(kCFAllocatorDefault,(CFURLRef)self,size,NULL);
return (CGImageRef) [NSMakeCollectable(image) autorelease];
}
```

Setting the thumbnail MAX SIZE to Apple defaults, it load all available thumbnails

```
(File: IMBCommon.h)

 // User Interface constants...

#define kIMBMaxThumbnailSize 1024.0
```

**Comment by mikeabdullah** [comment]
Hi, sorry I've only just gotten round to looking at this. Are you saying that `QLThumbnailImageCreate` is returning `nil` when using `kIMBMaxThumbnailSize`? And that we should instead be using "Apple defaults"? If so, what value do you mean by "Apple defaults"?

**Comment by loretoparisi** [comment]
Hi, If you set the following

#define kIMBMaxThumbnailSize 1024.0

it returns all the thumbnails

Here are you the diff

macbookproloreto:iMedia loreto$ git diff IMBCommon.h
diff --git a/IMBCommon.h b/IMBCommon.h
index ffee477..279ab1c 100644
--- a/IMBCommon.h
+++ b/IMBCommon.h
@@ -117,7 +117,7 @@ typedef NSUInteger IMBGroupType;

 // User Interface constants...

-#define kIMBMaxThumbnailSize 256.0
+#define kIMBMaxThumbnailSize 1024.0

 // Common error codes...

**Comment by mikeabdullah** [comment]
OK, fix implemented, thanks!
